# Group by and Aggregate Functions

Simple exercise based on [https://github.com/AlexTheAnalyst/PandasYouTubeSeries](https://github.com/AlexTheAnalyst/PandasYouTubeSeries)

*Visualisation Tip*
If you prefer the Jupyter Notebook render over VS Code's data wrangler, you can disable the `data wrangler output viewer` option in the settings. 
See [https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html](https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html) for more details.

**Student:** Jihye Park  
**Practice note:** I ran each cell in order and added short comments to record what I was checking.

In [1]:
import pandas as pd

In [2]:
## Read CSV from GitHub url
url = 'https://raw.githubusercontent.com/AlexTheAnalyst/PandasYouTubeSeries/main/Flavors.csv'
df = pd.read_csv(url)
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [ ]:
## Explore the data
# I first check the size, column names, data types, and missing values
# so I know what kind of aggregation is possible.
print(f'Rows: {df.shape[0]}, Columns: {df.shape[1]}')
print('\nColumn names:')
print(df.columns.tolist())
print('\nData types:')
print(df.dtypes)
print('\nMissing values by column:')
print(df.isna().sum())
df.head()

Rows: 9, Columns: 6

Column names:
['Flavor', 'Base Flavor', 'Liked', 'Flavor Rating', 'Texture Rating', 'Total Rating']

Data types:
Flavor                str
Base Flavor           str
Liked                 str
Flavor Rating     float64
Texture Rating    float64
Total Rating      float64
dtype: object

Missing values by column:
Flavor            0
Base Flavor       0
Liked             0
Flavor Rating     0
Texture Rating    0
Total Rating      0
dtype: int64

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2

In [ ]:

base_flavor_groups = df.groupby('Base Flavor')
list(base_flavor_groups.groups.keys())

['Chocolate', 'Vanilla']

In [ ]:
## Make this a new dataframe (grouped object)
grouped_df = df.groupby('Base Flavor')
# size() counts every row in each group, including rows with null values.
group_sizes = grouped_df.size().to_frame(name='Number of Flavors')
group_sizes

             Number of Flavors
Base Flavor
Chocolate                    3
Vanilla                      6

### My observation

`Vanilla` has 6 rows, while `Chocolate` has 3. I used `size()` first because it directly answers how many rows belong to each group.

In [ ]:
# count() works column by column and does not count missing values.
grouped_df.count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [ ]:
## Let's get the means for each Base Flavor
# Only the rating columns are numeric, so I use numeric_only=True.
grouped_df.mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

### My observation

The mean `Total Rating` is higher for the Chocolate base-flavor group than for Vanilla in this small dataset. I also noticed that `mean()` should be applied only to numeric columns.

In [ ]:
df.groupby('Base Flavor').mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [ ]:
grouped_df.agg(['count', 'sum', 'min', 'max'])

            Flavor                                                     \
             count                                                sum
Base Flavor
Chocolate        3          ChocolateRocky RoadChocolte Fudge Brownie
Vanilla          6  Mint Chocolate ChipVanillaCookie DoughPistachi...

                                     Liked                             \
                     min         max count              sum  min  max
Base Flavor
Chocolate      Chocolate  Rocky Road     3        YesYesYes  Yes  Yes
Vanilla      Cake Batter     Vanilla     6  YesNoYesNoYesNo   No  Yes

            Flavor Rating                  Texture Rating                  \
                    count   sum  min   max          count   sum  min  max
Base Flavor
Chocolate               3  25.2  8.2   8.8              3  21.7  7.0  7.6
Vanilla                 6  34.2  2.3  10.0              6  33.9  3.4  8.0

            Total Rating
                   count   sum   min   max
Base Flavor
Chocolate              3  47.1  15.2  16.6
Vanilla                6  68.1   5.7  18.0

In [ ]:
grouped_df.agg({
    'Flavor Rating': ['mean', 'min', 'max'],
    'Texture Rating': ['mean', 'min', 'max'],
    'Total Rating': ['count', 'mean', 'sum']
})

## Success? Commit changes to the repository!

            Flavor Rating            Texture Rating           Total Rating  \
                     mean  min   max           mean  min  max        count
Base Flavor
Chocolate             8.4  8.2   8.8       7.233333  7.0  7.6            3
Vanilla               5.7  2.3  10.0       5.650000  3.4  8.0            6


              mean   sum
Base Flavor
Chocolate    15.70  47.1
Vanilla      11.35  68.1

In [ ]:

df.groupby(['Base Flavor', 'Liked']).mean(numeric_only=True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333

In [ ]:

df.groupby(['Base Flavor', 'Liked']).agg({
    'Flavor': 'count',
    'Flavor Rating': ['mean', 'max'],
    'Texture Rating': ['mean', 'max'],
    'Total Rating': ['mean', 'sum']
})

                  Flavor Flavor Rating       Texture Rating      Total Rating  \
                   count          mean   max           mean  max         mean
Base Flavor Liked
Chocolate   Yes        3           8.4   8.8       7.233333  7.6    15.700000
Vanilla     No         3           3.6   4.7       4.466667  5.0     8.066667
            Yes        3           7.8  10.0       6.833333  8.0    14.633333


                    sum
Base Flavor Liked
Chocolate   Yes    47.1
Vanilla     No     24.2
            Yes    43.9

### My observation

Grouping by both `Base Flavor` and `Liked` makes the comparison more detailed. There is no Chocolate/No row in this dataset, so pandas only displays combinations that actually exist.

In [ ]:

grouped_df.describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]

### What I learned

`groupby()` performs the **split** step, functions such as `mean()` or `agg()` perform **apply**, and pandas joins the group results in the **combine** step. Saving the grouped object is convenient when I want to try several calculations on the same groups.